# exec-once = fcitx5
# exec-once = waybar & hyprpaper
# exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = playerctld daemon
exec-once = quickshell
exec-once = hypridle
exec-once = hyprpaper
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent

# Clipboard manager
exec-once = wl-paste --watch cliphist store

exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24

# VPN-CORE
exec-once = pkexec /home/zenyyxz/dotfiles/vpn/arch-vpn/vpn-core

