# exec-once = fcitx5
# exec-once = waybar & hyprpaper
# exec-once = systemctl --user start hyprpolkitagent
exec-once = playerctld daemon
exec-once = quickshell
exec-once = hypridle
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent

# Clipboard manager
exec-once = wl-paste --watch cliphist store


