# Preloads and wallpaper settings are managed by walt
# This config primarily disables the hyprpaper splash text

splash = false
ipc = on

# exec-once = sleep 1 && hyprctl hyprpaper reload ,$(cat ~/.cache/walt/current)


preload = /home/zenyyxz/Pictures/Wallpapers/anime-girl-nun-with-tattoo-4k-wallpaper-uhdpaper.com-740@3@a.jpg
wallpaper {
	monitor = eDP-1
	path = ~/Pictures/Wallpapers/wallhaven-zyqvpo.jpg
	fit_mode = cover
}
