### Window rules ###

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# Btop system monitor
windowrule {
	name = floating-btop
	match:title = ^(floating_btop)$
	float = on
	size = 1200 800
	center = on
}

# Yazi file manager
windowrule {
	name = floating-yazi
	match:class = ^(floating_yazi)$
	float = on
	size = 1200 800
	center = on
}

# Gnome-calc
windowrule {
	name = gnome-calc-float-rule
	match:initial_class = ^(org.gnome.calculator)$
	float = on
	size = 360 500
	opacity = 0.9 0.8
}

# Throne
windowrule {
	name = throne-float-rule
	match:class = ^(Throne)$
	float = on
	size = 1000 600
}

# Zenyyxz Agent
windowrule {
	name = Zenyyxz-Agent-float-rule
	match:title = ^(Zenyyxz Agent)$
	float = on
	size = 1200 800
}


