# Catppuccin Mocha theme for Fish
set -l foreground cdd6f4
set -l selection 313244
set -l comment 7f849c
set -l red f38ba8
set -l orange fab387
set -l yellow f9e2af
set -l green a6e3a1
set -l purple cba6f7
set -l cyan 89dceb
set -l pink f5c2e7

set -g fish_color_normal $foreground
set -g fish_color_command $purple
set -g fish_color_param $foreground
set -g fish_color_keyword $red
set -g fish_color_quote $green
set -g fish_color_redirection $pink
set -g fish_color_end $orange
set -g fish_color_error $red
set -g fish_color_gray $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $pink
set -g fish_color_autosuggestion $comment
set -g fish_color_cancel $red
set -g fish_color_cwd $yellow
set -g fish_color_user $cyan
set -g fish_color_host $purple
set -g fish_pager_color_prefix $pink
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
set -g fish_pager_color_progress $comment
set -g fish_pager_color_secondary $comment
